[project]
name = "python-source-analyser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dataclasses>=0.8",
    "dataclasses-json>=0.6.7",
]

[dependency-groups]
dev = [
	"ruff>=0.14.8",
	"mypy>=1.19.0",
]
